import { Point } from "@noble/secp256k1";
import { InvalidPayRequestError, NodePubkeyMismatchError } from "./errors";
import { unknownToRecord } from "./internal";
import type {
  Bolt11PayeeNodeIdSource,
  NodePubkey,
  NodePubkeyPolicy,
  NodePubkeyVerification,
  PayRequest,
} from "./types";

const compressedSecp256k1PubkeyPattern = /^(02|03)[0-9a-f]{64}$/i;

export type Bolt11PayeeNodeInfo = {
  payeeNodeId: string;
  payeeNodeIdSource: Bolt11PayeeNodeIdSource;
};

function normalizeNodePubkey(value: unknown, label: string): string {
  if (typeof value !== "string") {
    throw new InvalidPayRequestError(`${label} must be a string`);
  }

  const normalized = value.toLowerCase();
  if (!compressedSecp256k1PubkeyPattern.test(normalized)) {
    throw new InvalidPayRequestError(
      `${label} must be a compressed secp256k1 public key encoded as 66 hex characters`,
    );
  }

  try {
    Point.fromHex(normalized).assertValidity();
  } catch (cause) {
    throw new InvalidPayRequestError(`${label} must be a valid secp256k1 public key`, {
      cause,
    });
  }

  return normalized;
}

export function parseNodePubkeys(raw: unknown): NodePubkey[] | undefined {
  if (raw === undefined) {
    return undefined;
  }

  if (!Array.isArray(raw)) {
    throw new InvalidPayRequestError("nodePubkeys must be an array");
  }

  if (raw.length === 0) {
    throw new InvalidPayRequestError("nodePubkeys must contain at least one entry");
  }

  const seen = new Set<string>();
  const nodePubkeys: NodePubkey[] = [];

  for (const [index, entry] of raw.entries()) {
    const record = unknownToRecord(entry);
    if (!record) {
      throw new InvalidPayRequestError(`nodePubkeys entry ${index} must be an object`);
    }

    const pubkey = normalizeNodePubkey(record.pubkey, `nodePubkeys entry ${index}.pubkey`);
    if (seen.has(pubkey)) {
      throw new InvalidPayRequestError(`nodePubkeys contains duplicate pubkey: ${pubkey}`);
    }
    seen.add(pubkey);

    nodePubkeys.push({ pubkey, raw: record });
  }

  return nodePubkeys;
}

export function verifyNodePubkeys(
  payRequest: PayRequest,
  invoice: Bolt11PayeeNodeInfo,
  policy: NodePubkeyPolicy = "warn",
): NodePubkeyVerification | undefined {
  if (policy === "off" || !payRequest.nodePubkeys) {
    return undefined;
  }

  const expectedPubkeys = payRequest.nodePubkeys.map((entry) => entry.pubkey);
  const matchedPubkey = expectedPubkeys.find((pubkey) => pubkey === invoice.payeeNodeId);

  if (matchedPubkey) {
    return {
      status: "verified",
      payeeNodeId: invoice.payeeNodeId,
      payeeNodeIdSource: invoice.payeeNodeIdSource,
      expectedPubkeys,
      matchedPubkey,
    };
  }

  const warning =
    "This invoice was not generated by an expected node. The service advertised one set of nodes, but this invoice came from a different node. Proceed only if you trust the recipient.";

  if (policy === "enforce") {
    throw new NodePubkeyMismatchError(warning);
  }

  return {
    status: "mismatch",
    payeeNodeId: invoice.payeeNodeId,
    payeeNodeIdSource: invoice.payeeNodeIdSource,
    expectedPubkeys,
    warning,
  };
}
